### ISSUE TITLE
Urgent - All extensions disappeared from the instant search results

### ISSUE THREAD

**Issue by tassosm** [joomla/jed-issues#147]
This morning I noticed [all my extensions](https://extensions.joomla.org/profile/profile/details/230046/#extensions) disappeared from the instant search results. They do appear in the standard Joomla category views though. 

Take, for example, [EngageBox](https://extensions.joomla.org/extension/style-a-design/popups-a-iframes/engage-box). It does appear in the [iFrame & Popups](https://extensions.joomla.org/tags/popups-iframes/) and in the [Top Rated](https://extensions.joomla.org/browse/top-rated/) pages but if you search for it using either the keyword "EngageBox" or "popup" in the instant search, it doesn't show up.

The same goes for the rest of my extensions. 

This is very critical to my business and I hope it will be fixed soon.

**Comment by Ruud68** [comment]
Hi, facing exact the same issue for my extensions. furthermore if you type eg opengraph in the search box you get all sorts of unrelated extensions. So I think that the search is broken...

**Comment by regularlabs** [comment]
These also do not appear in the search results when searching through the form:
https://extensions.joomla.org/instant-search/?search-home=engagebox&q=engagebox

Seems like the indexing went haywire.

**Comment by anibalsanchez** [comment]
I'm investigating the issue. It looks like something went wrong in the indexing process.

**Comment by anibalsanchez** [comment]
I reverted a recent change that generated a JSON encoding error and broke the nightly indexing process.

Now, the process has been completed successfully.

Thanks for reporting!

**Comment by tassosm** [comment]
Thank you! It now works.

I noticed the search rankings are different a little bit now. Have you introduced any changes to the ranking factors?

**Comment by anibalsanchez** [comment]
Yes, this weekend I solved a search issue tweaking the order of ranking factors #113 

This is the new configuration: https://github.com/joomla/jed-issues/wiki/JED-Search-use-cases-and-definitions

**Comment by tassosm** [comment]
This is happening again. Can anyone take a look?

**Comment by anibalsanchez** [comment]
@tassosm I'm no longer a JED Team member.

**Comment by mfleeson** [comment]
@tassosm Please can you check now, I think I've repaired the algolia dataset.

**Comment by tassosm** [comment]
It was working a few hours ago. Now it is broken again.

**Comment by mfleeson** [comment]
Thanks for letting me know @tassosm The cron script crashed again with
Magick: quitting due to signal 1 (SIGHUP) "Hangup"...

I have manually run the script and it went through completely. I'm going to disable the cron update whilst I investigate

**Comment by tassosm** [comment]
Once again, my extensions disappeared. @mfleeson

**Comment by mfleeson** [comment]
Hi @tassosm 
All fixed now. Once again the algolia update script crashed mid-update.

**Comment by tassosm** [comment]
It's partially fixed. Only EngageBox works. 

Convert Forms, Advanced Custom Fields, and Google Structured Data do not appear in the search results.
