### ISSUE TITLE
Top Rated Extension broken?

### ISSUE THREAD

**Issue by brianteeman** [joomla/jed-issues#196]
For as long as I can remember Akeeba Backup from @nikosdion has been the number 1 rated extension.

Today it is not even in the first 6 pages but it is still the number 1 most reviewd extension.

I can only assume that there is some bug in the top rated extension code

**Comment by anibalsanchez** [comment]
Thanks for reporting. We've also noticed the inconsistency and we are working on an update.

We haven't changed this area recently, so the issue has been probably caused by a recent update.

**Comment by nikosdion** [comment]
This must be very recent (last few days at most) because the number of visits originating from JED has remained pretty steady since June. I am not comparing it to earlier months because we always see visits slow down from mid-June to mid-September the past ten years.

**Comment by anibalsanchez** [comment]
Fixed.

The change in the top extensions wasn't caused by a recent update, and it was caused due to the accumulated history of unpublished extensions and reviews.

In the [scoring algorithm](https://docs.google.com/presentation/d/1YTUvhYEK-bxoEE5-vJsjv06kZAvhpsAjSRmsY2w9GkU/edit#slide=id.g21ec0048aa_0_8), the average number of reviews is a critical parameter that applies different rules and weights. Until now, the average has been mostly a constant number, but it is calculated dynamically and it has been decreasing for years due to the accumulated number of unpublished reviews and extensions. It is rounded, so it wasn't even detected. In the past days, it dropped a whole point so it affected the scores.

I have applied a fix to take into account into the average only the currently published extensions and reviews, and the scores are back to normal.

Thanks for reporting. Case closed.

**Comment by brianteeman** [comment]
Almost fixed

On the JED itself I can see its fixed but in the joomla installer there is still a problem with the default display sorting of "JED Default" so I guess the same fix needs to be applied in an additional place

![image](https://user-images.githubusercontent.com/1296369/91642570-57253580-ea24-11ea-9868-a4f3f4151766.png)

![image](https://user-images.githubusercontent.com/1296369/91642572-5a202600-ea24-11ea-8367-df089ae72b3c.png)

**Comment by anibalsanchez** [comment]
The Joomla installer loads the information from the site. So, I guess it is cached somewhere (not in JED servers), so we must wait until it is refreshed.

**Comment by anibalsanchez** [comment]
IFW is back in sync with the JED Top listings. Case closed.

**Comment by brianteeman** [comment]
Thanks very much. Confirming its fixed
