### ISSUE TITLE
[JED] Reviews disappearing 

### ISSUE THREAD

**Issue by Radek-Suski** [joomla/jed-issues#8]
Hi,

several weeks ago I got a notification about new review at JED. I checked it few hours later and couldn't see any new review. I thought it was some kind of false notification and ignored it. 
Yesterday I got another notification and checked it almost immediately; the review was there. But several hours later my wife wanted to see it too and it wasn't there anymore. 
Could anybody check it please?

Regards,
Radek

PS: what's sendgrid.net?

**Comment by royhaanen** [comment]
Hi,

I have similar issues. For my extension ampz (https://extensions.joomla.org/extension/ampz/) I received an email about a new review on April 28th. Similar to Radek I didn't see a new review, but the count was increased with 1 (so it has counted somehow). Today I received another email and now the review got through, but the count is not increased...

Please check and advise.

Thank you.

Best regards,
Roy

**Comment by JazParkyn** [comment]
The JED has experienced huge volumes of SPAM reviews and we have taken measures to reduce this. Sadly the implementation we currently have with means that all reviews are published initially which triggers the email to let you know you have a review. Then a batch process runs which checks the new reviews and makes decisions about whether they should remain published or be removed. Unfortunately this process cannot retrieve the email which has already been sent.

We hope to improve this process in the future so that you are not alerted to what ends up being a non existent review, but at present we have to work with the tools that we have.

Please, open a ticket on JED about your extension(s) so we can look into the reviews for you.

(sendgrid is a transactional email service)

**Comment by royroosterz** [comment]
Hi Jaz,

Thank you for the reply. I am glad you are taking SPAM so serious since it is affecting us all. At the moment the SPAM filter is working a bit too good though ;-). 

I will open a ticket since I am sure some reviews are legitimate reviews.

By the way...can I offer the JED to use AMPZ as social sharing extension (https://www.roosterz.nl/joomla-extensions/ampz)?

Thanks again and have a great weekend!

Best regards,
Roy

**Comment by anibalsanchez** [comment]
Hi,

Concerning to the "disappearing" reviews:

- There is a batch process that validates reviews
- This process is executed asynchronously
- The result of the validation can unpublish a review
- Reviews are always published immediately after a user submits them, but it can be unpublished after a random period of time. (_Yes, it is done in this way on purpose... otherwise it would be easy to confirm if a spambot works fine_).

To improve the process, we are changing how the notifications are handled.

**Comment by weeblr** [comment]
Hi all,

I have see this behavior happening to one of my extensions just recently: received 2 emails in a row, went immediately to JED and reviews were not there. I understand the SPAM filtering has to be there, but basedon user mentionning iton our support, I'm pretty sure at least one of them was not spam (I can't be sure 100% they did post the review, but they sounded like they were doing it).

All anti-SPAM system has false positive, would it be considered to put those reviews in an unpublished state, or in a specific area where they can ve manually reviewed (by us of course, not asking you do that).

Rgds

**Comment by Radek-Suski** [comment]
I agree. The review I saw (that was removed later) was a genuine review with nothing suspicious in it. Yet it was later removed

**Comment by Llewellynvdm** [comment]
I have also seen good reviews never see the light, clients who told me directly that they appreciated my components and has rated them on the index, found there reviews never being published, and in most cases I know about, they were real people who made legitimate reviews and later asked me why I did not approve their review. See they thought it was me blocking it for some strange reason.

So I say this spam filter is hurting the Joomla community and needs to be **reviewed**, is that not ironic.

**Comment by tassosm** [comment]
Still happening on a daily basis. Unfortunately, I've lost more than 15 legit reviews the last months. 

I've noticed the following 3 cases here. 

1. The review is published but after 2-3 hours is no longer there for some reason.
2. The review is not published at all.
3. The review is not published but the counter gets increased and it remains increased.

In most cases, I do receive an email notification from JED and a follow-up e-mail from the customer who wrote the review.

**Comment by anibalsanchez** [comment]
Please, read my previous comment with the description of the JED Review checker https://github.com/joomla/jed-issues/issues/8#issuecomment-307347288

There are several ways that a legit review can be flagged as a spam review. For instance, if the user copy-pastes the same text in all fields ("It's perfect!")... then it is a fake review. Basically, "it looks like spam". You can submit a ticket for a manual review.... but if it really looks like spam, then it is not republished.

**Comment by Llewellynvdm** [comment]
@anibalsanchez I don't get it, if legit reviews is being flagged, **o wait dumped**, then the JED review checker is not working for us but against us. Please read my previous [#8 (comment)](https://github.com/joomla/jed-issues/issues/8#issuecomment-431084262) and you will see the whole issue is that we don't agree that dumping legit reviews is just okay, no matter the reason. Action is needed here.

I mean if a legit user wants to post _"It's perfect!"_ they should be allowed to, yes they should be allowed to copy past all they like, it is not against any laws, it is a **free** country right. Seriously trying to catch spammers should not dump legit reviews. We have to find a way to **allow legit users** to count in this community instead of suffering the blow intended for those who mean harm.

It is that simple. We extension developers work hard to get our products out there, most of which in my case are free. Then to hear _O well legit reviews get spammed because "it's prefect!"_ is not that reassuring to say the least. It is not like we tell our extension-users here is the five points on doing great reviews, and O, by the way don't do this and this and this or you will be flagged as spam. No what we do instead, if we are honest, is just build perfect/great extensions and do our share of maintaining them, and giving great support, so our extension-users will appreciate our work enough to support us with their reviews. This is not small task and is in most cases all we get for our hard work.

Then boom they get dumped **though they are legit** and so live goes on. **Really?** just sorry it looked like spam. This issue was opened April 2017... that is more then a year ago.

We have to do better then that. You can not ignore this issue any longer. I mean we appreciate the JED team, and I know you are doing all you can.

But clearly it is to much for just the JED team to look at all the reviews and have a life. Why not let the extension developers vote on the legitimacy of a review. They are the engine of JED, without them there is no JED.

So we lower the JED review checker just a tiny bit, so it does not just dump the review, but instead flag it. Then if flagged it sends to three other extension developers (not the owner of the extension), who gets to vote if it is legit (they must also have active extensions in the JED). They get send all the needed info to make a judgment call and if two agree it is legit then it gets published. With a simple link in an email (they must also not know who else are voting with them). Then the extension owner gets notified that the review was voted as spam, as a final step to in sure trust (that there is no favoritism in the system). Then only if the extension owner responds with a ticket does the JED team get involved.

I have build many systems like this it is so easy to do... **really we must help the extension developers get the gratitude they deserve**. We know Joomla is a community so the solution must involve a community effort, and it should not fall on just a few... 
I am sure if extension developers were made aware that this will become the new way of dealing with reviews that are not 100% sure is spam, but looks suspicious. They will go for it, if they know their own extension reviews will also now enjoy more attention.

Without the extension developers Joomla is not going anywhere, and believe me it is pretty discouraging if your projects does not get noticed because some so called JED review checker (app) keeps dumping your reviews wile you full well know they were legit.

I realized there is a flaw in the system when I started hearing back from my extension-users, who knows how many more have fallen through the cracks. It is not like we extension developers get notified of each review that was dumped, so by leaks we noticed this. That means you at JED know the true magnitude of the problem. Now a year later nothing has changed, or has it?
@tassosm says he still notices it on a daily basis.

Help me here I want to understand... Why is Joomla hurting it self? Since by dumping legit reviews its own extension directory is the worse for it. I understand the problem is spam... but the solution can never be that legit emails/reviews/users end up in the trash.

**Comment by Llewellynvdm** [comment]
This is crazy @anibalsanchez, we can't lower the bar? and yet that also means we lose the purpose of JED reviews, for it can never really reflect to true value of its extensions. How can we submit a ticket if we don't even know there was a review that was dumped. If our own clients contact us and say... we submitted a review, but it was dumped because I would not disclose my location. Then I realize what was suppose to just be a simple, I like and this is why... has become a spy tool that can possibly infringe upon its users privacy, and become something it was never intended to be.

I hear the noise spammers, spammers... and they are among us (wow so we are all now the enemy, except you of course). But to me it just sounds like a reasons to enforce control that over reach. I don't agree with the idea that danger/spam should corrode our freedoms. If three developers who have no relationship with the extension developer (that we know of, since they have never shared the same IP, or email domain) votes a review to be legit... that is more then enough. Don't give me that, it will not work because we can't trust anyone... why should we trust you then? Are you not also just another extension developer who like all of us start getting involved in the community?

We must be thinking smarter here. No one has ever solved these kind of trust issues without trusting... I mean is that not what voting is all about, trust? So we as developers have lost our trust in the program (JED review checker) we would rather trust fellow extension developers. If three is not enough, then make it five with three votes as pass. But just making every one a villain will end up placing us all in prison.

I would at this time say no use continuing the conversation if you refuse to see the other side. Truly your side is already in play... there is a system and it is dumping legit reviews at times. So we can assume that we agree spam is not good, point taken. But punishing the well meaning real legit reviewer is just as bad, if not worse! If you refuse to see that with comments like "we can't lower the bar" why keep this issue open? Just close it so we can know were we stand.

I would like to believe we are all working to achieve the same goal. **NO spam with EASY reviewing processes that are TRANSPARENT. So that great Joomla extensions get NOTICED by the community it SERVES.**

If any one of us have any other agenda then that, we will not succeed. So I stress our goal is not a JED review checker, or a high bar. But that **great extension get noticed by the community it servers**.

**Comment by nikosdion** [comment]
I disagree that a free-for-all review submission process is a good idea. This is what WordPress effectively does and it has not led to better ratings. In fact, there is a massive amount of really idiotic bad reviews and blatantly fake looking positive reviews. I believe the problem is that no software directory has ever done user testing to figure out what persuades and what dissuades people from filing a review when they _do not_ have extremely strong feelings or money to make out of doing so.

The biggest problem I see from the user's perspective is that the current JED implementation requires them to rate _and review_ a minimum of four(?) separate areas of the software, on a scale of 0-100, having to write a different piece of text on each and every section. A legitimate, average user can't be bothered to do that. That takes too much time and thinking. They will OBVIOUSLY select the same rating and copy-paste the same generic comment everywhere. They are there to thank the developer or make a mild complaint about what they perceive as a challenge, not write their memoirs.

The only people who will bother going through the time consuming process of filling everything in are:

1. The few people who received an overwhelmingly great experience (through the use or the support of the extension). This sparked enough joy in them to justify spending 10' for a simple review.
2. The few people who had an overwhelmingly bad experience -- typically because they were looking for something the extension doesn't do, doesn't says it does and they couldn't be bothered reading -- and feel outraged and self-righteous enough to spend 10' to file a bad review.
3. Spammers who are paid per piece of submitted spam.

That is to say, the real user, the person whose opinion we _truly_ need in the directory (be it positive or negative) is not going to file a review and rating. They are going to stay away. This is bad for us developers, it's bad for our users, it's bad for Joomla.

Note: before JED implemented the complicated system we were receiving a good 2-3 reviews a month. Now it's down to 1 review every 2-3 months and half of these seem to vanish. Our sales and free of charge downloads have gone up since then and we do have new people using our software so, obviously, it's not a matter of not having enough users for our software! It's a JED problem and that's what our users tell us when they bother to come back to us to say how much they liked our software but how much they hated the JED review process :(

JED reviews are not a marketing survey. The best way forward would be going back to the single 1-5 star rating and a single review field. Let people rate their **overall** experience with the extension and the developer, factoring in what matters to them, not you. It also makes figuring out spam far easier using third party anti-spam services.

That's my two cents _as someone who talked to real world users_. Obviously, my business case is best served by JED killing off most new submissions since I already have a great rating. But what's best for me in the short term is not fair to everyone else and, in the long term, for the project's whose success is vital for my long term business viability.

In the end of the day, do some user testing with real world users (NOT developer and JED staff!). You will see these challenges and possibly some more. The necessary actions to be taken will be dead obvious, I can guarantee it.

**Comment by anibalsanchez** [comment]
@nikosdion We all agree that we need to simplify the current system. In the recent updates, we have started to implement a star-based system. The complete migration away from the current 0-100 scale will take several more steps since it was included in the original system design, and it is ingrained in several parts of the site.

Thank you for your feedback, I've just opened a new Issue #66 about the topic to follow it there (or for future reference just paste your feedback there too).

**Comment by Llewellynvdm** [comment]
@nikosdion sure... I can agree with what you said. My whole point was not how to deal with the issue (reviews disappearing), but that there is an issue. What I suggested (what you called free-for-all reviews) was just ideas... and hey I did not even know that is how WordPress does it... hmmm interesting.

@anibalsanchez I am also saying thank you :+1:

**Comment by stevejburge** [comment]
We've been on the losing end of this with a good number of lost reviews of the years. But, I understand where the JED team is coming from and thank them for their work.

Just for context, this disappearing review problem is a few years old. Some sample links:
https://forum.joomla.org/viewtopic.php?f=262&t=940920
https://joomlaextensionsdirectory.atlassian.net/browse/JDEV-1060?jql=
https://joomlaextensionsdirectory.atlassian.net/browse/JDEV-1058?jql=
https://joomlaextensionsdirectory.atlassian.net/browse/JDEV-1052?jql=

**Comment by anibalsanchez** [comment]
**UPDATE**: We have redefined and reorganized the process of the review checkup. Now, reviews are not published until all controls are passed.

In these weeks, we are monitoring the new process. Overall, the original issue is solved.

**Comment by tassosm** [comment]
@anibalsanchez is there any change in the spam filter rules or the developer will no longer receive an email notification if a review is marked as spam?

**Comment by anibalsanchez** [comment]
The spam detection process is unchanged. It accepts/blocks the same case cases than before. In the field, we confirm that they are actively preventing spam reviews.

The recommendations are the same:

**Allowed and Encouraged**

- A full evaluation of the extension
- Courtesy and Honesty
- Pros & Cons of the extension and its performance
- Level of support received
- Ease of usage and deployment
- Purpose of using the extension (i.e., I used this extension for a magazine site.)
- Level of difficulty
- Your experience level with Joomla and web technologies

**Not allowed**

- Commercial disputes
- Questions to the Developer or Others
- Support/Feature Requests
- Error Messages
- Links
- Code or Bug Reports
- Questionable Language (including cursing)
- Submissions via an IP masking service or VPN
- One-line Reviews
- Self-promotion or spam

**Comment by anibalsanchez** [comment]
The review notification issue has been solved and we haven't received more reports.

Issue closed.

**Comment by tassosm** [comment]
Still happening..

Yesterday I got a notification stating that my extension [Google Structured Data](https://extensions.joomla.org/extensions/extension/search-a-indexing/web-search/google-structured-data-markup/) received a review as you can see in the screenshot above:

<img width="924" alt="screenshot 2019-01-27 at 18 24 27" src="https://user-images.githubusercontent.com/6807469/51803719-e4a90e00-2260-11e9-9068-fbfc2d1935ec.png">

I visited JED but the review was not there. I received the notification on 26th Jan but the last published review is from 24th Jan.

![google structured data markup by tassos marinos joomla extension directory](https://user-images.githubusercontent.com/6807469/51803758-508b7680-2261-11e9-9b96-e1303c224eb0.png)

**Comment by anibalsanchez** [comment]
@tassosm Let me review the case.

**Comment by anibalsanchez** [comment]
@tassosm Yes, the notifications are sent when all checks are passed. So, you received the notification about that review, when it was processed and published.

I'm going to adjust the job to increase the speed. Thanks for your feedback.

**Comment by tassosm** [comment]
You're welcome. I need a clarification, though.

If all checks have been passed why the review is not published? What job needs to be adjusted?

**Comment by anibalsanchez** [comment]
Reviews are published immediately after all checks are passed.

Notifications are sent by a daily process after the Review Checker. 

So, I think that now we need to adjust the processing windows to accelerate the notifications. Right now, there are messages sent after two days. In your case, you were confused by the time delay, not relating the notification with the last review.

I think that the best schedule is one daily notification per extension. So, confirmation of new reviews is received and it's a summary of the activity.

**Comment by Llewellynvdm** [comment]
@anibalsanchez I think the idea:

> So, confirmation of new reviews is received and it's a summary of the activity.

Will be stunning! That is if I understand correctly that "a summary of the activity" means more info over why the review was **approved, or rejected**. Specially when those reviews are not 100% spam.

**I therefore still think** the option to notify developers why a review **was not approved**, is very much needed. **They can turn it off** in their JED profile if they don't want to get it. But this way we can choose to help checkup the system. Transparency has always resolved question, and established trust, if the system is working well this should just establish trust.

Allowed and Encouraged

    A full evaluation of the extension
    Courtesy and Honesty
    Pros & Cons of the extension and its performance
    Level of support received
    Ease of usage and deployment
    Purpose of using the extension (i.e., I used this extension for a magazine site.)
    Level of difficulty
    Your experience level with Joomla and web technologies

Not allowed

    Commercial disputes
    Questions to the Developer or Others
    Support/Feature Requests
    Error Messages
    Links
    Code or Bug Reports
    Questionable Language (including cursing)
    Submissions via an IP masking service or VPN
    One-line Reviews
    Self-promotion or spam

Why not show us this in action, if that is the agreed approval and disapproval paths, then why not with the review, send the checkbox of why reviews are discarded.

@nikosdion I disagree with you that transparency is a bad idea. I must say reading [your reply](https://github.com/joomla/jed-issues/issues/8#issuecomment-453013566) I was almost sure I made a mistake commenting on this issue in the first place.

But today I strongly would object! I will once again make it very clear that I do not agree that this issue is resolved. Now you can close this ticket, and you can tell us it is resolved. But unless clear prove is given we can't know for sure.

Transparency is the only real answer, why do you think one of the biggest CMS use that method (@nikosdion a fact I did not even know [back then](https://github.com/joomla/jed-issues/issues/8#issuecomment-440107912)), and why are **they the biggest today**! @nikosdion when I started out working with Joomla, it was on top! I just yesterday received word from one of the biggest audio websites in the world, when I was pushing them to do a Joomla component as a client for their API (I build their API), they said no one who use their system is using Joomla... they instead want to target WordPress... That after I spend hours with their lead developers to reasons why Joomla is the best choice. They pointed to WordPress and the size of its community, based the number of plugins and the transparency they see there, they said, "you can build it one for Joomla, but we will only pay to get it done for WordPress". You know what that means? another component developed for free for Joomla, I can to do that, but others can not!

I am pleading with you we must be open to get head, we just must!

My loyalties is with the Joomla community, I have refused to change, I have walked away from big business to underline my support of this project. Why is it so hard to see that trust is the key to success here? We must regain the developers trust!!!!

If I am wrong... and all this is uncalled for, then I am also sorry! I just want to help improve the system... that is really all. I have no beef with any of you! Joomla being popular is what I want to achieve. So we must start with getting the developers back! They must trust us again! Transparency will be the easiest way to prove that we can be trusted!

**Comment by jreviews** [comment]
Notifications for new reviews stopped working again after a brief fix following #72 . Today a new review was published for one of my extensions and there was no email to go along with it. Looks like there was a regression to the recent fix.

**Comment by jreviews** [comment]
> I therefore still think the option to notify developers why a review was not approved, is very much needed. They can turn it off in their JED profile if they don't want to get it. But this way we can choose to help checkup the system. Transparency has always resolved question, and established trust, if the system is working well this should just establish trust.

I believe informing reviewers that their review was not approved and allowing them to update it for re-submission is also important and respects the time the reviewer put into writing his or her review in the first place. I believe the premise that a review is being submitted in good faith and that people make mistakes should be given more weight than the premise that every review that doesn't meet a criteria is spam and should be discarded.

**Comment by anibalsanchez** [comment]
Back to the original topic, the notifications are sent daily. If there are new reviews published, then you'll receive a notification per extension.

**Comment by jreviews** [comment]
@anibalsanchez Staying on topic, there is still an issue with notifications. 2 new reviews were published for one of my extensions. One on January 27, the other January 28. I did not receive an email notification for either one.

**Comment by anibalsanchez** [comment]
Let's wait for the daily process. I'm checking how much we can accelerate it. It looks like the current settings are too conservative.

**Comment by jreviews** [comment]
Just to clarify those reviews were published yesterday and day before yesterday. I waited until today before writing here to see if the notification arrived, and it didn't.

**Comment by anibalsanchez** [comment]
We have been monitoring the notifications and they are arriving after the reviews are published. 

So, reviews are no longer being unpublished after receiving notifications.

I still have to improve the speed of the process to send them on the same day (24 hs). I think that I'm going to implement the final enhancement this weekend.

So, issue closed.
